import '@element-plus/components/select/style/css'
import '@element-plus/components/checkbox/style/css'
import '@element-plus/components/scrollbar/style/css'
import '@element-plus/components/tooltip/style/css'
import '@element-plus/theme-chalk/el-permission-table.css'
